- .gitignore
- .travis.yml
- nature/tests.py
- nature/tests/test_models.py
- requirements-dev.txt
- setup.cfg
Setup Configuration file: setup.cfg
Devevelopment requirements: requirements-dev.txt
Add dummy tests (We need to manage the models before creating proper tests)
> Add various files for project configuration

- nature/admin.py
Also add search box and filters to features as the list of features is quite large.
Refs: #15
> Allow searching species when creating observations for features

- nature/admin.py
- nature/tests/test_admin.py
- nature/tests/utils.py
Allow adding feature classes, feature links and feature publications in admin
> Feature link

- nature/admin.py
> Make the map larger and default location to Helsinki

- nature/api.py
> Add feature link serializer

- nature/admin.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/57
> Remove actions from admin setups

- README.md
It's required to run both add_alter_columns.sql and add_id_seq.sql
no refs
> Update README.md with sql scripts

- nature/forms.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/54
> Use text area fields for name, description and notes

- nature/forms.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/46
> Order feature classes in feature admin form

- nature/admin.py
- nature/models.py
- nature/tests/test_models.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/55
> Format area in admin form

- nature/api.py
- nature/migrations/0001_initial.py
- nature/models.py
- nature/tests/factories.py
- nature/tests/test_models.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/49
> Rename Event models to Transaction

- ltj/settings.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/48
> Use fi timezone

- nature/admin.py
- nature/api.py
- nature/migrations/0001_initial.py
- nature/models.py
- nature/tests/factories.py
- nature/tests/test_models.py
Fixes https://github.com/City-of-Helsinki/ltj/issues/40
> Rename Mobility model to MigrationClass

- nature/static/nature/css/nature-ol.css
- nature/static/nature/js/NatureOLMapWidget.js
- nature/templates/nature/openlayers-nature.html
- nature/widgets.py
>  Add all necessary wmts base maps and a layer switcher

- ltj/settings.py
> Remove duplicated STATIC_URL setting entry

- nature/static/nature/js/NatureOLMapWidget.js
> Add attributions for wmts layers

- nature/static/nature/js/NatureOLMapWidget.js
Fixes https://github.com/City-of-Helsinki/ltj/issues/44
> Add title to geometry control buttons

- nature/admin.py
Admin pages for HabitatType, Regulation, Value, Transaction and Person are added.
Refs: #41
> Add admin pages for various registers

- nature/admin.py
- nature/forms.py
- nature/migrations/0001_initial.py
- nature/models.py
- nature/tests/factories.py
- nature/tests/test_models.py
> Allow adding feature values, feature transactions and habitat type observations to features

- README.md
- locale/fi/LC_MESSAGES/django.po
- ltj/settings.py
- nature/forms.py
- nature/models.py
- nature/tests/test_models.py
This should add translations for all user facing things in the admin interface
> Finnish translations for all models

- .travis.yml
> Install codecov for travis build

- nature/admin.py
> Set super_class read only

- ltj/settings.py
- requirements.txt
> Add sentry integration

- nature/forms.py
Previously form saving just crashes when editing protection fields if the related Protection instance does not exist at all.
The _save_m2m method is used internally by BaseInlineFormset in inline admin for saving new related instance. Thus we must override _save_m2m to make sure the m2m relations are saved via intermidate model manager.
no refs
> Relocate protection m2m saving from form save to _save_m2m

- nature/admin.py
- nature/static/nature/css/nature-ol.css
- nature/static/nature/js/NatureOLMapWidget.js
- nature/templates/admin/feature.html
- nature/templates/nature/openlayers-nature.html
- nature/tests/test_admin.py
This PR adds link to feature report in various places:
- Feature admin change form
- Feature admin list view
- Feature map WFS popup
> Add links to feature report

- nature/templates/nature/reports/feature-report.html
- nature/templates/nature/reports/stubs/observation-info.html
Some minor fixes:
- Do not display Linkki text in feature report transaction block if transaction does not have a link
- Add observation series to feature observation report
> Report fixes

- nature/urls.py
- nature/views.py
Change some report view names to be more explicit and consistent with other report views.
> Rename some of the report view names

- nature/templates/nature/reports/species-report.html
Some fields were not correctly aligned
> Minor report fix

- nature/templates/nature/reports/species-report.html
- nature/templates/nature/reports/stubs/observation-info.html
> Cleaning reports

- nature/views.py
This commit fixed following two issues in the ProtectedReportViewMixin and did minor refactoring.
- Previously it overrides the __init__ method without calling the base method. This may cause problems in some report views.
- The HMAC headers check logic seems to be wrong, the if condition would be True as long as HTTP_X_FORWARDED_GROUPS header exists.
I think I'll do another refactoring (after creating tests) to encapsulate the hmac logic into its own class and decouple it from views.
> Minor refactoring and fix a couple of errors

- nature/templates/nature/reports/feature-report.html
> Remove None text for text_display in feature report

- nature/templates/nature/reports/species-report.html
Closes #196 
Conditionally show `fid` instead of `id`
> Conditionally show fid instead of id

- nature/templates/nature/reports/stubs/species-regulation.html
> Change regulations

- locale/fi/LC_MESSAGES/django.po
- nature/templates/nature/reports/feature-report.html
- nature/templates/nature/reports/stubs/publication-info.html
Closes #155 
Add publications to feature report
> Add publications to feature report

- nature/templates/nature/reports/feature-report.html
Closes #156 
Added feature links to feature report
> Add feature links to feature report

- nature/templates/nature/reports/feature-observations-report.html
- nature/templates/nature/reports/feature-report.html
- nature/templates/nature/reports/species-report.html
> Change displaying of None-value fields

- requirements.txt
Closes #207 
Tests and manual tests pass.
> Upgrade Django to 2.1.7

- nature/admin.py
Closes #210 
Add regulation inlines for SpeciesAdmin, HabitatTypeAdmin and TransactionAdmin.
> Add regulation inlines for Species, HabitatType and Transaction admin models

- nature/templates/nature/reports/observationseries-report.html
- nature/templates/nature/reports/report-base.html
- nature/templates/nature/reports/species-report.html
Closes #215 
Add titles and filter out `None` values as described in the issue.
> Add titles and filter out None values

- nature/templates/nature/reports/feature-report.html
- nature/templates/nature/reports/stubs/observation-info.html
Closes #217 
Change document structure of feature report, according to issue.
> Change document structure of feature report

- nature/hmac.py
Closes #218 
Remove domain names from groups
> Remove domain names from groups

- locale/fi/LC_MESSAGES/django.po
- nature/static/nature/js/NatureOLMapWidget.js
- nature/templates/nature/openlayers-nature.html
Closes #190 
Make map editing a toggleable feature.
> Make map editing a toggleable feature

- locale/fi/LC_MESSAGES/django.po
- nature/templates/nature/reports/feature-report.html
- nature/templates/nature/reports/species-regulations-report.html
Termien käännösten viilaamista paremmin raportteihin sopiviksi ja muutama kentän näyttämiseen liittyvä muutos.
> Raporttien viilauksia

- nature/models.py
- nature/tests/test_models.py
Closes #214 
Implement separate `ObservationQuerySet` to take protection levels into account in `FeatureObservationsReportView`.
> Filter feature observations report

- nature/templates/nature/reports/feature-report.html
- nature/views.py
Closes #227 
- Inherit `ProtectedObservationListReportViewMixin` in `FeatureReportView`
- Implement `get_observation_queryset()` for `FeatureReportView`
> Take protection levels into account in FeatureReportView

- nature/models.py
Closes #234 
Change `__str__` method of `Regulation` and `HabitatType`
> Change __str__ method of Regulation and HabitatType

- nature/templates/nature/reports/feature-report.html
- nature/views.py
Closes #269 
Add regulations under transactions in feature report
> Add regulations under transactions in feature report

- nature/templates/nature/reports/feature-report.html
Fix typographical error in template
> Fix typographical error

- nature/views.py
Take staff users into account when displaying feature text
> Take staff users into account when displaying feature text

- nature/models.py
- nature/tests/test_models.py
> Include value field in Value instance str representation

- locale/fi/LC_MESSAGES/django.po
- templates/admin/base_site.html
> Regenerate translation files and update some translation text

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .vscode/launch.json
- .vscode/settings.json
- Dockerfile
- docker-compose.yml
- local_settings.py.tpl_dev
- postgis-initdb/prepare_database.sh
- requirements.in
- requirements.txt
- zshrc
Koodimuutos lisää nykyiselle ympäristölle VSCoden devcontainer pohjaisen kehitytympäristön
> Closes #361: VSCode pohjainen kehitysympäristö

- nature/admin.py
- nature/static/nature/css/nature-ol.css
- nature/widgets.py
Larger admin map and better visibility for layer selector when using dark mode
> Admin layout fixes to map widget

- nature/admin.py
- nature/forms.py
- nature/static/nature/js/NatureOLMapWidget.js
- nature/templates/admin/feature.html
- nature/templates/nature/openlayers-nature.html
This merge request returns the missing geometry tools used for the Feature view's map and sets the "Edit" / "Stop editing" button to match the state of editing functionality. The geometry tools were lost during the latest update of base class for FeatureAdmin. Said base class is within this merge request switch to yet another one, one that supports geometry tools. With this merge request also OpenLayer loading was updated so that in-case it would not work at the first time, OpenLayer loading will be tried from another source. This was done, as there were some issues with the loading.
The "Edit" / "Stop editing" button was working incorrectly, as the state of the view is editable upon the page load by definition and by the functionality available on the page. However, the said button …
> Map edit tools not rendered

- ltj/settings.py
This fixes the "Helsinki login" -method
```
TypeError: unsupported type for timedelta seconds component: str
```
> Fix social auth pipeline
