City-of-Helsinki/ltj

utility/add_alter_columns.sql
utility/add_id_seq.sql

Postgres version 9.5 and below does not support ADD COLUMN IF NOT EXIST synx. We relocate the column change script to sperate sql file so they both can be repeated.

Extract the column modification from the add_id_seq.sql

---

nature/admin.py

Replace feature_class with feature_class__name as the former doesn't allow text search.

Fix search_fields for FeatureAdmin

---

nature/models.py

We now have a common abstract base model for Feature and HistoricalFeature, and the `feature_class` field is moved to the base model. So we need to remove the related_name as we cannot create same related name for both `Feature` and `HistoricalFeature`.

Move feature_class field from abstract model to concrete models

---

ltj/settings.py
nature/api.py
requirements.txt

munigeo will create extra database tables that are not needed, and requires languages to be defined in settings.

Replace the munigeo.api.GeoModelSerializer with djangorestframework_gis

---

nature/admin.py

This is the easiest way to move it to the top without having to
define all of field in the model. If there is a need to order more
of the fields then all fields needs to be defined in the admin class.
Fixes https://github.com/City-of-Helsinki/ltj/issues/53

Move feature_class field to the top of the feature admin

---

nature/admin.py
nature/static/nature/js/NatureOLMapWidget.js
nature/templates/nature/openlayers-nature.html
nature/tests/test_widgets.py
nature/widgets.py

It  upgrades the openlayers version to the latest for feature geometry editing, and replace the default map to the wmts basemap.
This is the first step to implement #36. Django map widget and its template do not support multiple base layers and there's no built-in layer switcher in new version of openlayers. We need to tweak the widget and templates more and add a layer switcher to it.
Refs: #36

Upgrade openlayers to latest version and use basemap from kartta.hel.fi wmts service

---

ltj/settings.py

Current config does not actually set STATIC_{ROOT,URL} and MEDIA_{ROOT,URL}. They still need to be extracted from their variables.
Done using github editor, please double check.

Actually set STATIC_ROOT and MEDIA_ROOT

---

ltj/settings.py

Default Django logging (non-debug) only mails the admins. We want to send events to stderr. From there they can either be captured by the environment or seen by developer

Add a LOGGING configuration with output to stderr

---

nature/static/nature/css/nature-ol.css
nature/static/nature/js/NatureOLMapWidget.js

Add scale bar and coordinates to map.
The coordinates can of course still be moved around if this is not the best place. I just placed them as close to the previous position as possible, but since there is now the "info" entry at the bottom right I had to move the coordinates up a bit.
Fixes https://github.com/City-of-Helsinki/ltj/issues/51, https://github.com/City-of-Helsinki/ltj/issues/45

Map controls

---

nature/admin.py
nature/forms.py
nature/models.py
nature/tests/test_admin.py
nature/tests/test_forms.py
nature/tests/test_models.py

This PR added a new stacked inline form for protection fields at the bottom of feature form. A feature must be saved as a protected feature class first in order to edit protection fields.
Refs: #50

Adding protection fields to protected features

---

nature/models.py
nature/tests/test_models.py

Many criterion have same criterion, and it confuses users when selecting criteria for features.
no refs

Criterion string should also show specific_criterion and subcriterion when available

---

.gitignore
locale/fi/LC_MESSAGES/django.po
nature/admin.py
nature/forms.py
nature/models.py
nature/tests/test_admin.py
nature/tests/test_models.py

The square inline form is similar to protection inline form which is only display for specific type of features (the super class of feature's feature class is *RK*).
Refs: #89

Add square inline to feature form for square features

---

nature/admin.py
nature/forms.py

The texts are not using `ugettext_lazy` on purpose as there is no plan
on translating these fields to English.
Refs: https://github.com/City-of-Helsinki/ltj/issues/52

Add help texts for form fields

---

ltj/settings.py
nature/static/nature/js/NatureOLMapWidget.js
nature/templates/nature/openlayers-nature.html
nature/tests/test_views.py
nature/urls.py
nature/views.py
requirements.txt

This PR adds the feature wfs layers to feature editing map. The layers are separated by each feature classes, and the wfs layers are created from database views.
The WFS resources comes from remote WFS server and the django application serves as proxy for it. The main reason is that we need to keep the WFS resource private and make it available to authenticated users. This also makes it possible to do fine-grained access control for different type of users when needed. 
Currently WFS layers are rendered in Red-Green color scales and the target feature is rendered as blue to distinguish from the WFS features.
Deployment notes:
- Two setting variables are added which can be set form environment variables
**WFS_SERVER_URL** - remote wfs server url that the app can download wfs resources, the …

Add wfs layers to feature editing map

---

nature/static/nature/js/NatureOLMapWidget.js

Normally user want to turn on the layers that has the same feature class as the feature being updated

Turn off all WFS layers by default

---

nature/tests/test_views.py
nature/views.py

Staff usres have already access to all objects in the django admin. There is no reason to prevent them accessing non-open data reports.

Allow staff users access all reports

---

nature/admin.py
nature/templates/admin/species.html
nature/tests/test_admin.py

Species admin list display view:
Species admin change form view:

Add report links to Species admin list display and change form

---

nature/templates/nature/reports/feature-habitattypeobservations-report.html
nature/templates/nature/reports/feature-observations-report.html
nature/templates/nature/reports/feature-report.html
nature/templates/nature/reports/observation-report.html
nature/templates/nature/reports/species-regulations-report.html
nature/tests/test_views.py
nature/views.py

Previously all reports are using the target object's protection level as a suffix in the title, this should be changed to use the current user role.

Change to use user role instead of object protection level in report title

---

nature/templates/nature/reports/species-report.html

Closes #174 
Remove `taxon_2` field from `species_report.html` template.

Remove taxon_2 field from species report

---

locale/fi/LC_MESSAGES/django.po
ltj/settings.py
nature/forms.py

Closes #154 
Changed the translations according to issue. Problem was that fields mentioned in issue were actually Django forms, so they don't respect `verbose_name`, but `label` instead.

Change translations

---

nature/models.py

Closes #156 
- Fix feature links ordering feature by adding a default ordering number
- Take protection level into account when querying links related to features

Take protection level into account when querying links related to features

---

nature/models.py

Kannassa k.o. kenttä on not null, joten malli muutetaan vastaavaksi.

historiakohteen_kentan_null_muutos

---

requirements.txt

Closes #228 
Upgraded Django to newest LTS version 2.2.
Tests seem to pass as expected, and I could not produce any errors with manual testing.

Upgrade Django to newest LTS 2.2

---

nature/models.py
nature/tests/factories.py

Closes #249 
Removed unnecessary (duplicate) prefetches from `FeatureQuerySet`'s `for_office()` method. It turned out, `for_office()` method already got prefetches from `for_office_hki()` through super class.
Added links and transactions to test factories, so a bug like this would be caught in the future.

Remove unnecessary prefetches from for_office queryset

---

nature/templates/nature/reports/species-regulations-report.html
nature/templates/nature/reports/species-report.html
nature/templates/nature/reports/stubs/species-regulation.html
nature/views.py

Closes #248 
- Filter out invalid regulations
- Make regulation links open in a new tab
- Do not display None values in template

Species report filtering

---

requirements.txt

Closes #255 
Upgraded Django version to 2.2.7 in `requirements.txt`.

Upgrade django to 2.2.7 LTS

---

nature/hmac.py
nature/tests/test_hmac.py
templates/403.html

Raise 403 with message "Invalid Authorization" exceptions during HMAC-authorization in following cases:
- Hash supplied by the client is wrong
- Time given by the client is not within the clock skew

Handle invalid HMAC authentication and raise exceptions

---

nature/static/nature/js/NatureOLMapWidget.js

KYMP has changed their servers to use JHS180 tiling. Fix the admin map widget for that too.

Change admin map widget to use JHS180 tiling (ref b7ef9ca)

---

nature/templates/nature/reports/feature-report.html
nature/templates/nature/reports/report-base.html

Closes #274 
- Remove unnecessary hr element from footer
- Call for queryset instead of model manager in template's if-clause, to avoid rendering extra hr element when queryset returns no results

Adjust hr elements

---

nature/templates/nature/reports/feature-report.html
nature/views.py

Closes #277 
Display correct text fields for each user groups. Template logic was split into separate clauses (instead of `or`) for clarity.

Display correct text fields for each user type

---

imports/tests/test_models.py
nature/hmac.py
nature/tests/test_hmac.py

This PR fixes two problematic tests:
- Fix test__str__ in impors. The tests are run in random order and the test shapefile may have already been created when running test__str__. In such cases, an suffix will be appended to the filename to avoid collision.
- Raise InvalidAuthorization if invalid digest algorithm provided. The test that tests invalid hmac digest algorithm was failing because starting from Python 3.8, digestmod is a required parameter for HMAC. 
no refs

Fix python 3.8 failing tests

---

imports/admin.py
imports/importers.py
imports/tests/test_importers.py
imports/tests/test_validators.py
imports/tests/utils.py
imports/validators.py

This PR refactors the  ShapefileImporter to use Django's own DataSource API instead of the third party library. Django's DataSource API is nicer to work with and we do not need to worry about the compatibility issues when upgrading Django. And at the mean time it fixes the issue #267 
Refs: #267

Refactor shapefile import to use Django's own DataSource API

---

ltj/urls.py

The original path was copied from the `django-helusers` [documentation](https://github.com/City-of-Helsinki/django-helusers#adding-tunnistamo-authentication), which does not work.
Refs: #237

Fix the social_django path

---

ltj/settings.py
requirements.in
requirements.txt

`django-axes` has implemented the functionality that serves our purpose, so we will use the library instead instead of implementing the functionality by our own. `django-axes` provides functionality such as:
- records login attempts to your Django powered site and prevents attackers from attempting further logins to your site when they exceed the configured attempt limit.
- track the attempts and persist them in the database indefinitely, or alternatively use a fast and DDoS resistant cache implementation.
- can be configured to monitor login attempts by IP address, username, user agent, or their combinations.
- supports cool off periods, IP address whitelisting and blacklisting, user account whitelisting, and other features for Django access management.
See more details at …

Log failed login attempts using django-axes

---

imports/admin.py
imports/importers.py
imports/tests/test_admin.py
imports/tests/test_importers.py

The id field of Feature model is an AutoField, and we'll never
create a new feature with an id assigned in shapefiles. The id
value will be used to update existing features. And if the id
does not exist, a warning is raised to the user.
Refs: #267

Fix improper handling of the id field

---

nature/static/nature/js/NatureOLMapWidget.js

Previously Point editing was enabled when creating a new feature,
but users were not able to add point to the map. The problem is
that the button is active, but the actual interaction tool is not
activated. This commit disabled the active status on the Point
editing button.
Refs: #284

Disable default geometry type in feature admin map

---

nature/models.py
nature/templates/nature/reports/feature-report.html

Previously the Value `__str__` method is failing when explanation field has None value
Refs: #290

Fix Value __str__ method

---

imports/importers.py

Agreed with Sanna that admins will make sure that uploaded shapefiles are using the correct project (or no projection but with right geometry coordinates of the projection).
no refs

Remove mismatched srid warning

---

nature/hmac.py
nature/tests/test_hmac.py
nature/tests/test_views.py
nature/views.py

According to request specs (SpatialWeb client that request reports from ltj),
the X-forwarded-Group header is empty for 1) anonymous users (public
profile); 2) users who don't have nay roles. Thus a request without group
information or with invalid group information are vaild requests and can
access public reports. However, if a request that misses the Authorization
header or the authorization header is invalid, then the access should be denied.
Aslo the reports can only be accessed via spatial web proxy with hmac requests,
a normal django user is not able to access any reports.
Refs: #291

Improve the logic to handle invalid hmac requests

---

ltj/settings.py

Paging was broken by addition of duplicate DRF configuration dict
during implementation of token authentication.

Restore paging
